@DogApp.API_HostAddress = https://localhost:7117

GET {{DogApp.API_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{DogApp.API_HostAddress}}/track/CreateTrack
Content-Type: application/json

{
  
}

###
GET {{DogApp.API_HostAddress}}/track/GetAllTracks
Content-Type:application/json {}

###
POST {{DogApp.API_HostAddress}}/User/register
Content-Type:application/json {}

###
OPTIONS {{DogApp.API_HostAddress}}
Content-Type: application/json {}